# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/RNG_LFSR_final/netlist/sysgen_ip/RNG/RNG.srcs/sources_1/bd/rng/ip/rng_auto_pc_0/rng_auto_pc_0.xci
# IP: The module: 'rng_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/RNG_LFSR_final/netlist/sysgen_ip/RNG/RNG.srcs/sources_1/bd/rng/ip/rng_auto_pc_0/rng_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rng_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/RNG_LFSR_final/netlist/sysgen_ip/RNG/RNG.srcs/sources_1/bd/rng/ip/rng_auto_pc_0/rng_auto_pc_0.xci
# IP: The module: 'rng_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/RNG_LFSR_final/netlist/sysgen_ip/RNG/RNG.srcs/sources_1/bd/rng/ip/rng_auto_pc_0/rng_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rng_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
