# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/RI/rng_test01_ip/rng_test01_ip.srcs/sources_1/bd/design_1/ip/design_1_rng_test01_0_0/design_1_rng_test01_0_0.xci
# IP: The module: 'design_1_rng_test01_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/RI/rng_test01_ip/rng_test01_ip.srcs/sources_1/bd/design_1/ip/design_1_rng_test01_0_0/constrs/rng_test01.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rng_test01_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/RI/rng_test01_ip/rng_test01_ip.srcs/sources_1/bd/design_1/ip/design_1_rng_test01_0_0/design_1_rng_test01_0_0.xci
# IP: The module: 'design_1_rng_test01_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/RI/rng_test01_ip/rng_test01_ip.srcs/sources_1/bd/design_1/ip/design_1_rng_test01_0_0/constrs/rng_test01.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rng_test01_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
