# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/rng/rng.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rng || ORIG_REF_NAME==rng} -quiet] -quiet

# IP: bd/rng/ip/rng_processing_system7_0_0/rng_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rng_processing_system7_0_0 || ORIG_REF_NAME==rng_processing_system7_0_0} -quiet] -quiet

# IP: bd/rng/ip/rng_rng_0_0/rng_rng_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rng_rng_0_0 || ORIG_REF_NAME==rng_rng_0_0} -quiet] -quiet

# IP: bd/rng/ip/rng_auto_pc_0/rng_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rng_auto_pc_0 || ORIG_REF_NAME==rng_auto_pc_0} -quiet] -quiet

# IP: bd/rng/ip/rng_ps7_0_axi_periph_0/rng_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rng_ps7_0_axi_periph_0 || ORIG_REF_NAME==rng_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/rng/ip/rng_rst_ps7_0_100M_0/rng_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rng_rst_ps7_0_100M_0 || ORIG_REF_NAME==rng_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/rng/rng_ooc.xdc
